import Head from 'next/head'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import Portfolio from '../components/PortfolioShowcase'
import PortfolioProjects from '../components/PortfolioProjectx'
import PortfolioSub from '../components/PortfolioSub'

export default function About() {
    return(
        <div className='main portfolio'>
            <Head>
                <title>Abdurrahman Aderinto</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.ico" />
            </Head>
            <NavBar/>
            <Portfolio/>
            <PortfolioProjects/>
            <PortfolioSub/>
            <Footer/>
        </div>
    )
}